# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QCOM1.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FastbootFlashMainWin(object):
    def setupUi(self, FastbootFlashMainWin):
        FastbootFlashMainWin.setObjectName("FastbootFlashMainWin")
        FastbootFlashMainWin.resize(1067, 674)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../imag/updateFlash.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        FastbootFlashMainWin.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(FastbootFlashMainWin)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(512, 10, 449, 571))
        self.widget.setObjectName("widget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.checkBox_6 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_6.setText("")
        self.checkBox_6.setObjectName("checkBox_6")
        self.gridLayout_4.addWidget(self.checkBox_6, 6, 0, 1, 1)
        self.checkBox_5 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_5.setText("")
        self.checkBox_5.setObjectName("checkBox_5")
        self.gridLayout_4.addWidget(self.checkBox_5, 5, 0, 1, 1)
        self.spinBox_4 = QtWidgets.QSpinBox(self.widget)
        self.spinBox_4.setObjectName("spinBox_4")
        self.gridLayout_4.addWidget(self.spinBox_4, 3, 9, 1, 1)
        self.checkBox_37 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_37.setText("")
        self.checkBox_37.setObjectName("checkBox_37")
        self.gridLayout_4.addWidget(self.checkBox_37, 3, 3, 1, 1)
        self.checkBox_27 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_27.setText("")
        self.checkBox_27.setObjectName("checkBox_27")
        self.gridLayout_4.addWidget(self.checkBox_27, 6, 4, 1, 2)
        self.pushButton_12 = QtWidgets.QPushButton(self.widget)
        self.pushButton_12.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout_4.addWidget(self.pushButton_12, 5, 8, 1, 1)
        self.checkBox_38 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_38.setText("")
        self.checkBox_38.setObjectName("checkBox_38")
        self.gridLayout_4.addWidget(self.checkBox_38, 6, 3, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.widget)
        self.pushButton_11.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout_4.addWidget(self.pushButton_11, 6, 8, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_7.sizePolicy().hasHeightForWidth())
        self.lineEdit_7.setSizePolicy(sizePolicy)
        self.lineEdit_7.setMinimumSize(QtCore.QSize(200, 20))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout_4.addWidget(self.lineEdit_7, 6, 1, 1, 2)
        self.pushButton_7 = QtWidgets.QPushButton(self.widget)
        self.pushButton_7.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_4.addWidget(self.pushButton_7, 3, 8, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_5.sizePolicy().hasHeightForWidth())
        self.lineEdit_5.setSizePolicy(sizePolicy)
        self.lineEdit_5.setMinimumSize(QtCore.QSize(200, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_4.addWidget(self.lineEdit_5, 4, 1, 1, 2)
        self.checkBox_22 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_22.setObjectName("checkBox_22")
        self.gridLayout_4.addWidget(self.checkBox_22, 1, 5, 1, 2)
        self.checkBox_24 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_24.setText("")
        self.checkBox_24.setObjectName("checkBox_24")
        self.gridLayout_4.addWidget(self.checkBox_24, 2, 4, 1, 2)
        self.spinBox_3 = QtWidgets.QSpinBox(self.widget)
        self.spinBox_3.setObjectName("spinBox_3")
        self.gridLayout_4.addWidget(self.spinBox_3, 2, 9, 1, 1)
        self.checkBox_35 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_35.setText("")
        self.checkBox_35.setObjectName("checkBox_35")
        self.gridLayout_4.addWidget(self.checkBox_35, 2, 3, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_4.sizePolicy().hasHeightForWidth())
        self.lineEdit_4.setSizePolicy(sizePolicy)
        self.lineEdit_4.setMinimumSize(QtCore.QSize(200, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_4.addWidget(self.lineEdit_4, 3, 1, 1, 2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_3.sizePolicy().hasHeightForWidth())
        self.lineEdit_3.setSizePolicy(sizePolicy)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(200, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_4.addWidget(self.lineEdit_3, 2, 1, 1, 2)
        self.checkBox_29 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_29.setText("")
        self.checkBox_29.setObjectName("checkBox_29")
        self.gridLayout_4.addWidget(self.checkBox_29, 4, 4, 1, 2)
        self.pushButton_6 = QtWidgets.QPushButton(self.widget)
        self.pushButton_6.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_4.addWidget(self.pushButton_6, 2, 8, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 1, 7, 1, 2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_3.setText("")
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout_4.addWidget(self.checkBox_3, 3, 0, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_2.setText("")
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout_4.addWidget(self.checkBox_2, 2, 0, 1, 1)
        self.checkBox_26 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_26.setText("")
        self.checkBox_26.setObjectName("checkBox_26")
        self.gridLayout_4.addWidget(self.checkBox_26, 3, 4, 1, 2)
        self.pushButton_8 = QtWidgets.QPushButton(self.widget)
        self.pushButton_8.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_4.addWidget(self.pushButton_8, 4, 8, 1, 1)
        self.spinBox_5 = QtWidgets.QSpinBox(self.widget)
        self.spinBox_5.setObjectName("spinBox_5")
        self.gridLayout_4.addWidget(self.spinBox_5, 4, 9, 1, 1)
        self.checkBox_28 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_28.setText("")
        self.checkBox_28.setObjectName("checkBox_28")
        self.gridLayout_4.addWidget(self.checkBox_28, 5, 4, 1, 2)
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 1, 9, 1, 1)
        self.checkBox_4 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_4.setText("")
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout_4.addWidget(self.checkBox_4, 4, 0, 1, 1)
        self.spinBox_6 = QtWidgets.QSpinBox(self.widget)
        self.spinBox_6.setObjectName("spinBox_6")
        self.gridLayout_4.addWidget(self.spinBox_6, 5, 9, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_6.sizePolicy().hasHeightForWidth())
        self.lineEdit_6.setSizePolicy(sizePolicy)
        self.lineEdit_6.setMinimumSize(QtCore.QSize(200, 20))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_4.addWidget(self.lineEdit_6, 5, 1, 1, 2)
        self.checkBox_40 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_40.setText("")
        self.checkBox_40.setObjectName("checkBox_40")
        self.gridLayout_4.addWidget(self.checkBox_40, 4, 3, 1, 1)
        self.checkBox_39 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_39.setText("")
        self.checkBox_39.setObjectName("checkBox_39")
        self.gridLayout_4.addWidget(self.checkBox_39, 5, 3, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.widget)
        self.pushButton_10.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_4.addWidget(self.pushButton_10, 7, 8, 1, 1)
        self.checkBox_8 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_8.setText("")
        self.checkBox_8.setObjectName("checkBox_8")
        self.gridLayout_4.addWidget(self.checkBox_8, 8, 0, 1, 1)
        self.spinBox_7 = QtWidgets.QSpinBox(self.widget)
        self.spinBox_7.setObjectName("spinBox_7")
        self.gridLayout_4.addWidget(self.spinBox_7, 6, 9, 1, 1)
        self.spinBox_11 = QtWidgets.QSpinBox(self.widget)
        self.spinBox_11.setObjectName("spinBox_11")
        self.gridLayout_4.addWidget(self.spinBox_11, 10, 9, 1, 1)
        self.spinBox_8 = QtWidgets.QSpinBox(self.widget)
        self.spinBox_8.setObjectName("spinBox_8")
        self.gridLayout_4.addWidget(self.spinBox_8, 7, 9, 1, 1)
        self.spinBox_12 = QtWidgets.QSpinBox(self.widget)
        self.spinBox_12.setObjectName("spinBox_12")
        self.gridLayout_4.addWidget(self.spinBox_12, 11, 9, 1, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_9.sizePolicy().hasHeightForWidth())
        self.lineEdit_9.setSizePolicy(sizePolicy)
        self.lineEdit_9.setMinimumSize(QtCore.QSize(200, 20))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout_4.addWidget(self.lineEdit_9, 8, 1, 1, 2)
        self.checkBox_42 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_42.setText("")
        self.checkBox_42.setObjectName("checkBox_42")
        self.gridLayout_4.addWidget(self.checkBox_42, 12, 0, 1, 1)
        self.checkBox_23 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_23.setText("")
        self.checkBox_23.setObjectName("checkBox_23")
        self.gridLayout_4.addWidget(self.checkBox_23, 10, 4, 1, 2)
        self.pushButton_16 = QtWidgets.QPushButton(self.widget)
        self.pushButton_16.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout_4.addWidget(self.pushButton_16, 10, 8, 1, 1)
        self.checkBox_36 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_36.setText("")
        self.checkBox_36.setObjectName("checkBox_36")
        self.gridLayout_4.addWidget(self.checkBox_36, 11, 3, 1, 1)
        self.checkBox_21 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_21.setText("")
        self.checkBox_21.setObjectName("checkBox_21")
        self.gridLayout_4.addWidget(self.checkBox_21, 8, 4, 1, 2)
        self.spinBox_9 = QtWidgets.QSpinBox(self.widget)
        self.spinBox_9.setObjectName("spinBox_9")
        self.gridLayout_4.addWidget(self.spinBox_9, 8, 9, 1, 1)
        self.checkBox_30 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_30.setText("")
        self.checkBox_30.setObjectName("checkBox_30")
        self.gridLayout_4.addWidget(self.checkBox_30, 9, 4, 1, 2)
        self.checkBox_20 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_20.setText("")
        self.checkBox_20.setObjectName("checkBox_20")
        self.gridLayout_4.addWidget(self.checkBox_20, 7, 4, 1, 2)
        self.checkBox_32 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_32.setText("")
        self.checkBox_32.setObjectName("checkBox_32")
        self.gridLayout_4.addWidget(self.checkBox_32, 8, 3, 1, 1)
        self.spinBox_10 = QtWidgets.QSpinBox(self.widget)
        self.spinBox_10.setObjectName("spinBox_10")
        self.gridLayout_4.addWidget(self.spinBox_10, 9, 9, 1, 1)
        self.checkBox_11 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_11.setText("")
        self.checkBox_11.setObjectName("checkBox_11")
        self.gridLayout_4.addWidget(self.checkBox_11, 11, 0, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.widget)
        self.pushButton_9.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_4.addWidget(self.pushButton_9, 8, 8, 1, 1)
        self.checkBox_41 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_41.setText("")
        self.checkBox_41.setObjectName("checkBox_41")
        self.gridLayout_4.addWidget(self.checkBox_41, 9, 3, 1, 1)
        self.checkBox_9 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_9.setText("")
        self.checkBox_9.setObjectName("checkBox_9")
        self.gridLayout_4.addWidget(self.checkBox_9, 9, 0, 1, 1)
        self.checkBox_31 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_31.setText("")
        self.checkBox_31.setObjectName("checkBox_31")
        self.gridLayout_4.addWidget(self.checkBox_31, 7, 3, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(self.widget)
        self.pushButton_15.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout_4.addWidget(self.pushButton_15, 9, 8, 1, 1)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_12.sizePolicy().hasHeightForWidth())
        self.lineEdit_12.setSizePolicy(sizePolicy)
        self.lineEdit_12.setMinimumSize(QtCore.QSize(200, 20))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.gridLayout_4.addWidget(self.lineEdit_12, 11, 1, 1, 2)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_8.sizePolicy().hasHeightForWidth())
        self.lineEdit_8.setSizePolicy(sizePolicy)
        self.lineEdit_8.setMinimumSize(QtCore.QSize(200, 20))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout_4.addWidget(self.lineEdit_8, 7, 1, 1, 2)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_11.sizePolicy().hasHeightForWidth())
        self.lineEdit_11.setSizePolicy(sizePolicy)
        self.lineEdit_11.setMinimumSize(QtCore.QSize(200, 20))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout_4.addWidget(self.lineEdit_11, 10, 1, 1, 2)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_10.sizePolicy().hasHeightForWidth())
        self.lineEdit_10.setSizePolicy(sizePolicy)
        self.lineEdit_10.setMinimumSize(QtCore.QSize(200, 20))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout_4.addWidget(self.lineEdit_10, 9, 1, 1, 2)
        self.checkBox_10 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_10.setText("")
        self.checkBox_10.setObjectName("checkBox_10")
        self.gridLayout_4.addWidget(self.checkBox_10, 10, 0, 1, 1)
        self.checkBox_25 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_25.setText("")
        self.checkBox_25.setObjectName("checkBox_25")
        self.gridLayout_4.addWidget(self.checkBox_25, 11, 4, 1, 2)
        self.pushButton_14 = QtWidgets.QPushButton(self.widget)
        self.pushButton_14.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout_4.addWidget(self.pushButton_14, 11, 8, 1, 1)
        self.checkBox_34 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_34.setText("")
        self.checkBox_34.setObjectName("checkBox_34")
        self.gridLayout_4.addWidget(self.checkBox_34, 10, 3, 1, 1)
        self.checkBox_7 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_7.setText("")
        self.checkBox_7.setObjectName("checkBox_7")
        self.gridLayout_4.addWidget(self.checkBox_7, 7, 0, 1, 1)
        self.checkBox_46 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_46.setText("")
        self.checkBox_46.setObjectName("checkBox_46")
        self.gridLayout_4.addWidget(self.checkBox_46, 13, 3, 1, 1)
        self.checkBox_48 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_48.setText("")
        self.checkBox_48.setObjectName("checkBox_48")
        self.gridLayout_4.addWidget(self.checkBox_48, 14, 0, 1, 1)
        self.checkBox_50 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_50.setText("")
        self.checkBox_50.setObjectName("checkBox_50")
        self.gridLayout_4.addWidget(self.checkBox_50, 14, 4, 1, 2)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_17.sizePolicy().hasHeightForWidth())
        self.lineEdit_17.setSizePolicy(sizePolicy)
        self.lineEdit_17.setMinimumSize(QtCore.QSize(200, 20))
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.gridLayout_4.addWidget(self.lineEdit_17, 15, 1, 1, 2)
        self.checkBox_52 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_52.setText("")
        self.checkBox_52.setObjectName("checkBox_52")
        self.gridLayout_4.addWidget(self.checkBox_52, 15, 3, 1, 1)
        self.checkBox_53 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_53.setText("")
        self.checkBox_53.setObjectName("checkBox_53")
        self.gridLayout_4.addWidget(self.checkBox_53, 15, 4, 1, 2)
        self.spinBox_16 = QtWidgets.QSpinBox(self.widget)
        self.spinBox_16.setObjectName("spinBox_16")
        self.gridLayout_4.addWidget(self.spinBox_16, 15, 9, 1, 1)
        self.checkBox_54 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_54.setText("")
        self.checkBox_54.setObjectName("checkBox_54")
        self.gridLayout_4.addWidget(self.checkBox_54, 16, 0, 1, 1)
        self.lineEdit_18 = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_18.sizePolicy().hasHeightForWidth())
        self.lineEdit_18.setSizePolicy(sizePolicy)
        self.lineEdit_18.setMinimumSize(QtCore.QSize(200, 20))
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.gridLayout_4.addWidget(self.lineEdit_18, 16, 1, 1, 2)
        self.checkBox_55 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_55.setText("")
        self.checkBox_55.setObjectName("checkBox_55")
        self.gridLayout_4.addWidget(self.checkBox_55, 16, 3, 1, 1)
        self.checkBox_56 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_56.setText("")
        self.checkBox_56.setObjectName("checkBox_56")
        self.gridLayout_4.addWidget(self.checkBox_56, 16, 4, 1, 2)
        self.pushButton_24 = QtWidgets.QPushButton(self.widget)
        self.pushButton_24.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_24.setObjectName("pushButton_24")
        self.gridLayout_4.addWidget(self.pushButton_24, 14, 8, 1, 1)
        self.pushButton_26 = QtWidgets.QPushButton(self.widget)
        self.pushButton_26.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_26.setObjectName("pushButton_26")
        self.gridLayout_4.addWidget(self.pushButton_26, 16, 8, 1, 1)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_14.sizePolicy().hasHeightForWidth())
        self.lineEdit_14.setSizePolicy(sizePolicy)
        self.lineEdit_14.setMinimumSize(QtCore.QSize(200, 20))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.gridLayout_4.addWidget(self.lineEdit_14, 12, 1, 1, 2)
        self.spinBox_14 = QtWidgets.QSpinBox(self.widget)
        self.spinBox_14.setObjectName("spinBox_14")
        self.gridLayout_4.addWidget(self.spinBox_14, 13, 9, 1, 1)
        self.checkBox_44 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_44.setText("")
        self.checkBox_44.setObjectName("checkBox_44")
        self.gridLayout_4.addWidget(self.checkBox_44, 12, 4, 1, 2)
        self.pushButton_22 = QtWidgets.QPushButton(self.widget)
        self.pushButton_22.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_22.setObjectName("pushButton_22")
        self.gridLayout_4.addWidget(self.pushButton_22, 12, 8, 1, 1)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_15.sizePolicy().hasHeightForWidth())
        self.lineEdit_15.setSizePolicy(sizePolicy)
        self.lineEdit_15.setMinimumSize(QtCore.QSize(200, 20))
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.gridLayout_4.addWidget(self.lineEdit_15, 13, 1, 1, 2)
        self.checkBox_47 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_47.setText("")
        self.checkBox_47.setObjectName("checkBox_47")
        self.gridLayout_4.addWidget(self.checkBox_47, 13, 4, 1, 2)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_16.sizePolicy().hasHeightForWidth())
        self.lineEdit_16.setSizePolicy(sizePolicy)
        self.lineEdit_16.setMinimumSize(QtCore.QSize(200, 20))
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.gridLayout_4.addWidget(self.lineEdit_16, 14, 1, 1, 2)
        self.checkBox_49 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_49.setText("")
        self.checkBox_49.setObjectName("checkBox_49")
        self.gridLayout_4.addWidget(self.checkBox_49, 14, 3, 1, 1)
        self.spinBox_13 = QtWidgets.QSpinBox(self.widget)
        self.spinBox_13.setObjectName("spinBox_13")
        self.gridLayout_4.addWidget(self.spinBox_13, 12, 9, 1, 1)
        self.checkBox_51 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_51.setText("")
        self.checkBox_51.setObjectName("checkBox_51")
        self.gridLayout_4.addWidget(self.checkBox_51, 15, 0, 1, 1)
        self.spinBox_15 = QtWidgets.QSpinBox(self.widget)
        self.spinBox_15.setObjectName("spinBox_15")
        self.gridLayout_4.addWidget(self.spinBox_15, 14, 9, 1, 1)
        self.pushButton_25 = QtWidgets.QPushButton(self.widget)
        self.pushButton_25.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_25.setObjectName("pushButton_25")
        self.gridLayout_4.addWidget(self.pushButton_25, 15, 8, 1, 1)
        self.pushButton_23 = QtWidgets.QPushButton(self.widget)
        self.pushButton_23.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_23.setObjectName("pushButton_23")
        self.gridLayout_4.addWidget(self.pushButton_23, 13, 8, 1, 1)
        self.checkBox_45 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_45.setText("")
        self.checkBox_45.setObjectName("checkBox_45")
        self.gridLayout_4.addWidget(self.checkBox_45, 13, 0, 1, 1)
        self.checkBox_43 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_43.setText("")
        self.checkBox_43.setObjectName("checkBox_43")
        self.gridLayout_4.addWidget(self.checkBox_43, 12, 3, 1, 1)
        self.spinBox_17 = QtWidgets.QSpinBox(self.widget)
        self.spinBox_17.setObjectName("spinBox_17")
        self.gridLayout_4.addWidget(self.spinBox_17, 16, 9, 1, 1)
        self.checkBox_13 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_13.setObjectName("checkBox_13")
        self.gridLayout_4.addWidget(self.checkBox_13, 1, 0, 1, 2)
        self.pushButton_17 = QtWidgets.QPushButton(self.widget)
        self.pushButton_17.setObjectName("pushButton_17")
        self.gridLayout_4.addWidget(self.pushButton_17, 1, 2, 1, 1)
        self.checkBox_33 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_33.setObjectName("checkBox_33")
        self.gridLayout_4.addWidget(self.checkBox_33, 1, 3, 1, 2)
        self.label_12 = QtWidgets.QLabel(self.widget)
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 0, 6, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_4)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.pushButton_18 = QtWidgets.QPushButton(self.widget)
        self.pushButton_18.setObjectName("pushButton_18")
        self.horizontalLayout_25.addWidget(self.pushButton_18)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 0, 0, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.widget)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout_3.addWidget(self.spinBox, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 1, 0, 1, 1)
        self.spinBox_2 = QtWidgets.QSpinBox(self.widget)
        self.spinBox_2.setObjectName("spinBox_2")
        self.gridLayout_3.addWidget(self.spinBox_2, 1, 1, 1, 1)
        self.horizontalLayout_25.addLayout(self.gridLayout_3)
        self.gridLayout_2.addLayout(self.horizontalLayout_25, 0, 0, 1, 1)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.pushButton_19 = QtWidgets.QPushButton(self.widget)
        self.pushButton_19.setObjectName("pushButton_19")
        self.horizontalLayout_24.addWidget(self.pushButton_19)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.pushButton_20 = QtWidgets.QPushButton(self.widget)
        self.pushButton_20.setObjectName("pushButton_20")
        self.horizontalLayout_17.addWidget(self.pushButton_20)
        self.pushButton_21 = QtWidgets.QPushButton(self.widget)
        self.pushButton_21.setObjectName("pushButton_21")
        self.horizontalLayout_17.addWidget(self.pushButton_21)
        self.horizontalLayout_24.addLayout(self.horizontalLayout_17)
        self.gridLayout_2.addLayout(self.horizontalLayout_24, 1, 0, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_2)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(10, 10, 496, 523))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.widget1)
        self.label_3.setMaximumSize(QtCore.QSize(50, 20))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.comboBox = QtWidgets.QComboBox(self.widget1)
        self.comboBox.setMinimumSize(QtCore.QSize(150, 20))
        self.comboBox.setEditable(True)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_4.addWidget(self.comboBox)
        self.label_4 = QtWidgets.QLabel(self.widget1)
        self.label_4.setMaximumSize(QtCore.QSize(50, 20))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.comboBox_2 = QtWidgets.QComboBox(self.widget1)
        self.comboBox_2.setObjectName("comboBox_2")
        self.horizontalLayout_4.addWidget(self.comboBox_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_4.addWidget(self.pushButton_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.widget1)
        self.label_5.setMaximumSize(QtCore.QSize(50, 20))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.comboBox_3 = QtWidgets.QComboBox(self.widget1)
        self.comboBox_3.setObjectName("comboBox_3")
        self.horizontalLayout_3.addWidget(self.comboBox_3)
        self.label_6 = QtWidgets.QLabel(self.widget1)
        self.label_6.setMaximumSize(QtCore.QSize(50, 20))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.comboBox_4 = QtWidgets.QComboBox(self.widget1)
        self.comboBox_4.setObjectName("comboBox_4")
        self.horizontalLayout_3.addWidget(self.comboBox_4)
        self.label_7 = QtWidgets.QLabel(self.widget1)
        self.label_7.setMaximumSize(QtCore.QSize(50, 20))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.comboBox_6 = QtWidgets.QComboBox(self.widget1)
        self.comboBox_6.setObjectName("comboBox_6")
        self.horizontalLayout_3.addWidget(self.comboBox_6)
        self.label_8 = QtWidgets.QLabel(self.widget1)
        self.label_8.setMaximumSize(QtCore.QSize(50, 20))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.comboBox_5 = QtWidgets.QComboBox(self.widget1)
        self.comboBox_5.setObjectName("comboBox_5")
        self.horizontalLayout_3.addWidget(self.comboBox_5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.textBrowser = QtWidgets.QTextBrowser(self.widget1)
        self.textBrowser.setMinimumSize(QtCore.QSize(0, 120))
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_5.addWidget(self.textBrowser, 0, 0, 1, 1)
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.widget1)
        self.textBrowser_2.setMaximumSize(QtCore.QSize(16777215, 70))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.gridLayout_5.addWidget(self.textBrowser_2, 1, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.widget1)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.label = QtWidgets.QLabel(self.widget1)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_17 = QtWidgets.QCheckBox(self.widget1)
        self.checkBox_17.setObjectName("checkBox_17")
        self.gridLayout.addWidget(self.checkBox_17, 0, 0, 1, 1)
        self.checkBox_18 = QtWidgets.QCheckBox(self.widget1)
        self.checkBox_18.setObjectName("checkBox_18")
        self.gridLayout.addWidget(self.checkBox_18, 0, 1, 1, 2)
        self.checkBox_14 = QtWidgets.QCheckBox(self.widget1)
        self.checkBox_14.setObjectName("checkBox_14")
        self.gridLayout.addWidget(self.checkBox_14, 0, 3, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.widget1)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 0, 4, 1, 1)
        self.checkBox_15 = QtWidgets.QCheckBox(self.widget1)
        self.checkBox_15.setObjectName("checkBox_15")
        self.gridLayout.addWidget(self.checkBox_15, 1, 0, 1, 2)
        self.checkBox_16 = QtWidgets.QCheckBox(self.widget1)
        self.checkBox_16.setObjectName("checkBox_16")
        self.gridLayout.addWidget(self.checkBox_16, 1, 2, 1, 2)
        self.checkBox_19 = QtWidgets.QCheckBox(self.widget1)
        self.checkBox_19.setObjectName("checkBox_19")
        self.gridLayout.addWidget(self.checkBox_19, 1, 4, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.widget1)
        self.plainTextEdit.setMaximumSize(QtCore.QSize(16777215, 71))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.horizontalLayout_2.addWidget(self.plainTextEdit)
        self.pushButton_4 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_4.setMinimumSize(QtCore.QSize(0, 30))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../Send_72px_1191826_easyicon.net.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon1)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_2.addWidget(self.pushButton_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_5.addWidget(self.pushButton_2)
        self.lineEdit = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_5.addWidget(self.lineEdit)
        self.pushButton_5 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_5.addWidget(self.pushButton_5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.checkBox_12 = QtWidgets.QCheckBox(self.widget1)
        self.checkBox_12.setText("")
        self.checkBox_12.setObjectName("checkBox_12")
        self.horizontalLayout_6.addWidget(self.checkBox_12)
        self.pushButton_13 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_13.setMinimumSize(QtCore.QSize(70, 0))
        self.pushButton_13.setMaximumSize(QtCore.QSize(0, 16777215))
        self.pushButton_13.setObjectName("pushButton_13")
        self.horizontalLayout_6.addWidget(self.pushButton_13)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_13.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.horizontalLayout_6.addWidget(self.lineEdit_13)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        FastbootFlashMainWin.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(FastbootFlashMainWin)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1067, 23))
        self.menubar.setObjectName("menubar")
        FastbootFlashMainWin.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(FastbootFlashMainWin)
        self.statusbar.setObjectName("statusbar")
        FastbootFlashMainWin.setStatusBar(self.statusbar)

        self.retranslateUi(FastbootFlashMainWin)
        QtCore.QMetaObject.connectSlotsByName(FastbootFlashMainWin)

    def retranslateUi(self, FastbootFlashMainWin):
        _translate = QtCore.QCoreApplication.translate
        FastbootFlashMainWin.setWindowTitle(_translate("FastbootFlashMainWin", "FastbootFlashUpdate"))
        self.pushButton_12.setText(_translate("FastbootFlashMainWin", "4"))
        self.pushButton_11.setText(_translate("FastbootFlashMainWin", "5"))
        self.pushButton_7.setText(_translate("FastbootFlashMainWin", "2"))
        self.checkBox_22.setText(_translate("FastbootFlashMainWin", "Enter"))
        self.pushButton_6.setText(_translate("FastbootFlashMainWin", "1"))
        self.label_2.setText(_translate("FastbootFlashMainWin", "TextLabel"))
        self.pushButton_8.setText(_translate("FastbootFlashMainWin", "3"))
        self.label_11.setText(_translate("FastbootFlashMainWin", "Delay(ms)"))
        self.pushButton_10.setText(_translate("FastbootFlashMainWin", "6"))
        self.pushButton_16.setText(_translate("FastbootFlashMainWin", "8"))
        self.pushButton_9.setText(_translate("FastbootFlashMainWin", "7"))
        self.pushButton_15.setText(_translate("FastbootFlashMainWin", "9"))
        self.pushButton_14.setText(_translate("FastbootFlashMainWin", "10"))
        self.pushButton_24.setText(_translate("FastbootFlashMainWin", "13"))
        self.pushButton_26.setText(_translate("FastbootFlashMainWin", "15"))
        self.pushButton_22.setText(_translate("FastbootFlashMainWin", "11"))
        self.pushButton_25.setText(_translate("FastbootFlashMainWin", "14"))
        self.pushButton_23.setText(_translate("FastbootFlashMainWin", "12"))
        self.checkBox_13.setText(_translate("FastbootFlashMainWin", "全选"))
        self.pushButton_17.setText(_translate("FastbootFlashMainWin", "Clear ALL"))
        self.checkBox_33.setText(_translate("FastbootFlashMainWin", "HEX"))
        self.pushButton_18.setText(_translate("FastbootFlashMainWin", "Load Script"))
        self.label_9.setText(_translate("FastbootFlashMainWin", "Run Times"))
        self.label_10.setText(_translate("FastbootFlashMainWin", "Delay TIme(ms)"))
        self.pushButton_19.setText(_translate("FastbootFlashMainWin", "Save As"))
        self.pushButton_20.setText(_translate("FastbootFlashMainWin", "RUN"))
        self.pushButton_21.setText(_translate("FastbootFlashMainWin", "STOP"))
        self.label_3.setText(_translate("FastbootFlashMainWin", "UART1:"))
        self.comboBox.setCurrentText(_translate("FastbootFlashMainWin", "COM"))
        self.label_4.setText(_translate("FastbootFlashMainWin", "BaudRate："))
        self.pushButton_3.setText(_translate("FastbootFlashMainWin", "Open Port"))
        self.label_5.setText(_translate("FastbootFlashMainWin", "ByteSize"))
        self.label_6.setText(_translate("FastbootFlashMainWin", "FlowCtr"))
        self.label_7.setText(_translate("FastbootFlashMainWin", "StopBits"))
        self.label_8.setText(_translate("FastbootFlashMainWin", "Parity"))
        self.pushButton.setText(_translate("FastbootFlashMainWin", "Clear Info"))
        self.label.setText(_translate("FastbootFlashMainWin", "Input String"))
        self.checkBox_17.setText(_translate("FastbootFlashMainWin", "DTR"))
        self.checkBox_18.setText(_translate("FastbootFlashMainWin", "RTS"))
        self.checkBox_14.setText(_translate("FastbootFlashMainWin", "Show\\r\\n"))
        self.checkBox.setText(_translate("FastbootFlashMainWin", "Show Time"))
        self.checkBox_15.setText(_translate("FastbootFlashMainWin", "Show In HEX"))
        self.checkBox_16.setText(_translate("FastbootFlashMainWin", "HEX String."))
        self.checkBox_19.setText(_translate("FastbootFlashMainWin", "Send With Enter"))
        self.pushButton_4.setText(_translate("FastbootFlashMainWin", "发送"))
        self.pushButton_4.setShortcut(_translate("FastbootFlashMainWin", "Return"))
        self.pushButton_2.setText(_translate("FastbootFlashMainWin", "Select File"))
        self.pushButton_5.setText(_translate("FastbootFlashMainWin", "Send File"))
        self.pushButton_13.setText(_translate("FastbootFlashMainWin", "Save Log"))
